// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using feedme_csharp_mvc.Data;

#nullable disable

namespace feedme_csharp_mvc.Migrations
{
    [DbContext(typeof(FeedMeDbContext))]
    [Migration("20230506182639_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("feedme_csharp_mvc.Models.ChoiceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("choiceLists");
                });

            modelBuilder.Entity("feedme_csharp_mvc.Models.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ChoiceListId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChoiceListId");

                    b.ToTable("options");
                });

            modelBuilder.Entity("feedme_csharp_mvc.Models.Option", b =>
                {
                    b.HasOne("feedme_csharp_mvc.Models.ChoiceList", null)
                        .WithMany("Options")
                        .HasForeignKey("ChoiceListId");
                });

            modelBuilder.Entity("feedme_csharp_mvc.Models.ChoiceList", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
